version: '3.8'
name: 'complaint'
services:
  mongo:
    container_name: mongo
    restart: always
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 8c18e23138bc5240468600b2a646bda2958303d7c69bdfed94

  complaint:
    container_name: complaint
    restart: always
    image: complaint
    build: 
      context: ./chall
    links: 
      - mongo
    ports: 
      - "20203:20203"